# Capstone Project - The Battle of the Neighborhoods (Week 2)
## Applied Data Science Capstone by IBM/Coursera
### Downtown vs Suburbs comparison for the city of Santander 
#### by Angel San Emeterio Herrera


## Table of contents
* [Introduction: Business Problem](#introduction)
* [Data](#data)
* [Methodology](#methodology)
* [Analysis](#analysis)
* [Results and Discussion](#results)
* [Conclusion](#conclusion)

## Introduction: Business Problem <a name="introduction"></a>

In this project our goal will be to identify which streets in the furthest areas of the city of Santander, a medium size town in the north coast of Spain, are similar to the ones belonging to innermost downtown, in terms of venues and services. 

In other words, we will make a comparison between two zones of the city of Santander: most internal downtown (identify as the first postal code of the city, 39001) and most external suburbs (identify as the last postal code, 39012), in order to pinpoint which areas of the latter would be similar to the former, according to the closeness of settings and places of interest.

Given that the urban development in Spain, and more precisely in Santander, focus services and venues on the downtown, while leaving certain zones in the suburbs lacking places of interest, what we will try to do is finding out to what extent this is true for the case of Santander. 

That is to say, what we actually want to know is which streets in the most exterior area of the city of Santander are similar to the ones in the very center of the town.


## Data <a name="data"></a>

Based on the above definition of our problem, we will need:
- First of all, data on postal codes, streets and latitude and longitude about the city of Santander. To get this
  we will use **Santander city council's API**, located in the city open data repository.
  
- Secondly, data on venues and their location for the city of Santander, which will be provided by 
  using **Foursquare API**.

## Methodology <a name="methodology"></a>

We'll complete the project in several steps:

1) Get the geo data about the city of Santander, by calling the city council API 
   (http://datos.santander.es/api/rest/datasets/callejero_numpostales.json)
   The city provides the geo data in UTM format, so we will need to transform them into GPS coordinates (by means of
   utm library). We will end up by obtaining a clean dataset with just two postal codes and all of the streets belonging to    each one. The innermost one will be postal code 39001 while the furthest will be postal code 39012.

2) After that, we will use Foursquare API to get the venues associated with each of the locations (streets) which belongs      to each postal codes.

3) Then, we will make the comparison by making three complementary clustering analyis (by using **k-means clustering**):

    -analysis of the result with 2 clusters (minimum): given we have just two set of locations grouped by postal code
  
    -analysis of the result with 5 clusters (medium): as an intermediate solution, with more than double of the 
     original sets of data
  
    -analysis of the result with 20 clusters (maximum): in order to get the most dispersion for postal code 39012 and            least dispersion for postal code 39001.

We will present one map for each clustering option, to better show which of the areas of the furthest most suburb of the city of Santander are similar to the ones in the very center of the city.

## Analysis <a name="analysis"></a>

#### First, download all the libraries we will need

In [1]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json # library to handle JSON files

!conda install -c conda-forge geopy --yes  
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

!conda install -c conda-forge folium=0.5.0 --yes  
import folium # map rendering library

# libraries for web scraping
%pip install beautifulsoup4   
from bs4 import BeautifulSoup
import urllib.request

# Convert an UTM coordinate into a (latitude, longitude) tuple
import utm

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans


print('<<<<<<<<<<<<<<<<<<< Libraries imported >>>>>>>>>>>>>>>>>>>')

Solving environment: ...working... 
  - anaconda/win-64::openssl-1.1.1d-he774522_2
  - defaults/win-64::openssl-1.1.1d-he774522_2done

# All requested packages already installed.

Solving environment: ...working... 
  - anaconda/win-64::openssl-1.1.1d-he774522_2
  - defaults/win-64::openssl-1.1.1d-he774522_2done

# All requested packages already installed.

Note: you may need to restart the kernel to use updated packages.
<<<<<<<<<<<<<<<<<<< Libraries imported >>>>>>>>>>>>>>>>>>>


#### Get the data from the Santander city council open repository

In [2]:
url = "http://datos.santander.es/api/datos/callejero_numpostales.json"

results = requests.get(url).json()
results

{'summary': {'items': 13878,
  'items_per_page': 1000,
  'pages': 14,
  'current_page': 1},
 'resources': [{'callej:sigla': 'CL',
   'callej:distrito': '08',
   'rdf:type': 'callej:Numero-postal',
   'dct:spatial': 'POINT  ( 430592.56000000 4810310.05000000)',
   'gn:postalCode': '39011',
   'callej:portal-bis': ' ',
   'dc:modified': '2020-04-28T22:06:28.35Z',
   'callej:num-portal': '7',
   'callej:seccion': '020',
   'dc:identifier': '4728',
   'callej:nombre-clasif': 'FAUSTINO CAVADAS',
   'callej:portal-bloque': ' ',
   'callej:portal': ' ',
   'dc:description': '',
   'uri': 'http://datos.santander.es/api/datos/callejero_numpostales/2.json'},
  {'callej:sigla': 'CL',
   'callej:distrito': '08',
   'rdf:type': 'callej:Numero-postal',
   'dct:spatial': 'POINT  ( 429633.68000000 4813410.42000000)',
   'gn:postalCode': '39012',
   'callej:portal-bis': 'B',
   'dc:modified': '2020-04-28T22:06:28.35Z',
   'callej:num-portal': '6',
   'callej:seccion': '007',
   'dc:identifier': '3411',

In [3]:
# assign relevant part of JSON to venues
venues = results['resources']

# tranform venues into a dataframe
dataframe = json_normalize(venues)
dataframe.head()


callej:sigla callej:distrito              rdf:type  \
0           CL              08  callej:Numero-postal   
1           CL              08  callej:Numero-postal   
2           CL              08  callej:Numero-postal   
3           CL              08  callej:Numero-postal   
4           CL              07  callej:Numero-postal   

                                  dct:spatial gn:postalCode callej:portal-bis  \
0  POINT  ( 430592.56000000 4810310.05000000)         39011                     
1  POINT  ( 429633.68000000 4813410.42000000)         39012                 B   
2  POINT  ( 434920.66000000 4814743.53000000)         39012                     
3  POINT  ( 434890.16000000 4814688.66000000)         39012                     
4  POINT  ( 435178.29000000 4813424.31000000)         39006                     

               dc:modified callej:num-portal callej:seccion dc:identifier  \
0  2020-04-28T22:06:28.35Z                 7            020          4728   
1  2020-04-28T22:06:28.35Z                 6            007          3411   
2  2020-04-28T22:06:28.35Z               162            012          1399   
3  2020-04-28T22:06:28.35Z               174            012          1399   
4  2020-04-28T22:06:28.35Z                62            012           172   

   callej:nombre-clasif callej:portal-bloque callej:portal dc:description  \
0      FAUSTINO CAVADAS                                                     
1        COSTA QUEBRADA                                                     
2         INES D. NOVAL                                                     
3         INES D. NOVAL                                                     
4  FERNANDO DE LOS RIOS                                                     

                                                 uri  
0  http://datos.santander.es/api/datos/callejero_...  
1  http://datos.santander.es/api/datos/callejero_...  
2  http://datos.santander.es/api/datos/callejero_...  
3  http://datos.santander.es/api/datos/callejero_...  
4  http://datos.santander.es/api/datos/callejero_...

In [4]:
# keep only columns with relevant information
filtered_columns = ['callej:sigla','callej:distrito','dct:spatial','gn:postalCode','callej:seccion','callej:nombre-clasif']
dataframe_filtered = dataframe.loc[:, filtered_columns]
dataframe_filtered.head()

callej:sigla callej:distrito                                 dct:spatial  \
0           CL              08  POINT  ( 430592.56000000 4810310.05000000)   
1           CL              08  POINT  ( 429633.68000000 4813410.42000000)   
2           CL              08  POINT  ( 434920.66000000 4814743.53000000)   
3           CL              08  POINT  ( 434890.16000000 4814688.66000000)   
4           CL              07  POINT  ( 435178.29000000 4813424.31000000)   

  gn:postalCode callej:seccion  callej:nombre-clasif  
0         39011            020      FAUSTINO CAVADAS  
1         39012            007        COSTA QUEBRADA  
2         39012            012         INES D. NOVAL  
3         39012            012         INES D. NOVAL  
4         39006            012  FERNANDO DE LOS RIOS

In [5]:
# rename colummns
dataframe_filtered.rename(columns = {'callej:sigla':'StreetType','callej:distrito':'District','dct:spatial':'Coordinates','gn:postalCode':'PostalCode','callej:seccion':'Section','callej:nombre-clasif':'StreetName'}, inplace = True)
dataframe_filtered.head()

StreetType District                                 Coordinates PostalCode  \
0         CL       08  POINT  ( 430592.56000000 4810310.05000000)      39011   
1         CL       08  POINT  ( 429633.68000000 4813410.42000000)      39012   
2         CL       08  POINT  ( 434920.66000000 4814743.53000000)      39012   
3         CL       08  POINT  ( 434890.16000000 4814688.66000000)      39012   
4         CL       07  POINT  ( 435178.29000000 4813424.31000000)      39006   

  Section            StreetName  
0     020      FAUSTINO CAVADAS  
1     007        COSTA QUEBRADA  
2     012         INES D. NOVAL  
3     012         INES D. NOVAL  
4     012  FERNANDO DE LOS RIOS

In [6]:
# only process records with district postal code not null

# to keep records with Postal Code not null (length > 1)
dataframe_filtered = dataframe_filtered[dataframe_filtered['PostalCode'].map(len) > 1].reset_index(drop=True)
dataframe_filtered.to_excel("test_filtered.xlsx")
print(dataframe_filtered.shape)

(970, 6)


In [7]:
dataframe_filtered

StreetType District                                 Coordinates  \
0           CL       08  POINT  ( 430592.56000000 4810310.05000000)   
1           CL       08  POINT  ( 429633.68000000 4813410.42000000)   
2           CL       08  POINT  ( 434920.66000000 4814743.53000000)   
3           CL       08  POINT  ( 434890.16000000 4814688.66000000)   
4           CL       07  POINT  ( 435178.29000000 4813424.31000000)   
5           CL       08  POINT  ( 430363.59000000 4811007.80000000)   
6           AV       08  POINT  ( 431483.33000000 4810345.64000000)   
7           CL       08  POINT  ( 429610.03000000 4813102.36000000)   
8           CL       05  POINT  ( 433512.12000000 4811648.78000000)   
9           CL       08  POINT  ( 431163.14000000 4812256.02000000)   
10          CL       02  POINT  ( 433552.97000000 4812701.48000000)   
11          AV       08  POINT  ( 431337.22000000 4812455.24000000)   
12          CL       06  POINT  ( 433993.09870000 4812468.38810000)   
13          CL       06  POINT  ( 433852.82000000 4812302.87000000)   
14          CL       07  POINT  ( 432514.19000000 4812869.14000000)   
15          CL       07  POINT  ( 432780.93000000 4812766.87000000)   
16          AV       06  POINT  ( 432833.44000000 4811856.84000000)   
17          CL       07  POINT  ( 432826.24000000 4812776.99000000)   
18          CL       08  POINT  ( 432008.96000000 4812496.29000000)   
19          CL       08  POINT  ( 431422.48090000 4811914.24520000)   
20          CL       08  POINT  ( 429654.80680000 4811548.37070000)   
21          CL       04  POINT  ( 437027.00820000 4813593.81500000)   
22          CL       08  POINT  ( 431188.36040000 4811858.40000000)   
23          CL       08  POINT  ( 433476.50000000 4813782.56000000)   
24          CL       08  POINT  ( 430454.11000000 4813432.70000000)   
25          CL       05  POINT  ( 434225.90000000 4811990.50000000)   
26          CL       08  POINT  ( 432538.03830000 4814221.52130000)   
27          CL       08  POINT  ( 430041.46000000 4813144.45000000)   
28          CL       08  POINT  ( 430355.48000000 4813417.13000000)   
29          CL       08  POINT  ( 434014.47230000 4813919.38020000)   
30          AV       08  POINT  ( 430529.33660000 4810509.80710000)   
31          CL       08  POINT  ( 429453.58000000 4811031.22000000)   
32          CL       08  POINT  ( 430005.26000000 4811566.26000000)   
33          CL       08  POINT  ( 430108.25000000 4811685.53000000)   
34          PS       07  POINT  ( 434675.16960000 4813329.91560000)   
35          AV       04  POINT  ( 436178.31790000 4814026.08160000)   
36          CL       08  POINT  ( 430563.68100000 4810599.67710000)   
37          CL       05  POINT  ( 434498.46910000 4812211.28150000)   
38          CL       08  POINT  ( 434601.83000000 4814876.35000000)   
39          CL       08  POINT  ( 432891.08000000 4813668.26000000)   
40          CL       04  POINT  ( 436233.70000000 4812853.65000000)   
41          PS       03  POINT  ( 435299.27000000 4813254.74000000)   
42          PS       03  POINT  ( 435630.46000000 4813098.49000000)   
43          CL       08  POINT  ( 429829.98000000 4811034.92000000)   
44          CL       08  POINT  ( 434338.26700000 4814420.70330000)   
45          AV       08  POINT  ( 435792.97630000 4814956.76150000)   
46          AV       04  POINT  ( 436977.71790000 4813649.00180000)   
47          CL       08  POINT  ( 434298.70160000 4814407.90550000)   
48          BJ       07  POINT  ( 434119.52000000 4813246.92000000)   
49          CL       01  POINT  ( 434956.77000000 4812829.47000000)   
50          CL       01  POINT  ( 434515.70000000 4812602.65000000)   
51          CL       04  POINT  ( 437170.65000000 4813362.91000000)   
52          AV       04  POINT  ( 436681.56000000 4812918.60000000)   
53          CL       02  POINT  ( 432163.42000000 4812154.83000000)   
54          PZ       05  POINT  ( 433705.84760000 4811464.76230000)   
55          AV       04  POI

In [8]:
# eliminate POINT() and split coordinates into 2 columns

# eliminate POINT()
dataframe_filtered['Coordinates'] = dataframe_filtered['Coordinates'].str.replace(r'POINT', '')
dataframe_filtered['Coordinates'] = dataframe_filtered['Coordinates'].str.replace(r'(', '')
dataframe_filtered['Coordinates'] = dataframe_filtered['Coordinates'].str.replace(r')', '')

# split coordinates into 2 columns
# by default it splits on single space 
dataframe_filtered[['Lat_UTM','Long_UTM']] = dataframe_filtered.Coordinates.str.split(expand=True) 

dataframe_filtered.drop(['Coordinates'], axis = 1, inplace=True)

dataframe_filtered.head()


StreetType District PostalCode Section            StreetName  \
0         CL       08      39011     020      FAUSTINO CAVADAS   
1         CL       08      39012     007        COSTA QUEBRADA   
2         CL       08      39012     012         INES D. NOVAL   
3         CL       08      39012     012         INES D. NOVAL   
4         CL       07      39006     012  FERNANDO DE LOS RIOS   

           Lat_UTM          Long_UTM  
0  430592.56000000  4810310.05000000  
1  429633.68000000  4813410.42000000  
2  434920.66000000  4814743.53000000  
3  434890.16000000  4814688.66000000  
4  435178.29000000  4813424.31000000

In [9]:
dataframe_filtered.shape

(970, 7)

In [10]:
dataframe_filtered.head()

StreetType District PostalCode Section            StreetName  \
0         CL       08      39011     020      FAUSTINO CAVADAS   
1         CL       08      39012     007        COSTA QUEBRADA   
2         CL       08      39012     012         INES D. NOVAL   
3         CL       08      39012     012         INES D. NOVAL   
4         CL       07      39006     012  FERNANDO DE LOS RIOS   

           Lat_UTM          Long_UTM  
0  430592.56000000  4810310.05000000  
1  429633.68000000  4813410.42000000  
2  434920.66000000  4814743.53000000  
3  434890.16000000  4814688.66000000  
4  435178.29000000  4813424.31000000

In [11]:
# Bidirectional UTM-WGS84 converter for python http://pypi.python.org/pypi/utm
# To get WGS84 (geographical lat/long) coordinates

# Spain's UTM zone, which are required parameters for the call to utm.to_latlon
# https://epsg.io/3042

gps_lat = dataframe_filtered['Lat_UTM']
gps_long = dataframe_filtered['Long_UTM']
gps_coordinates =[]

# get the GPS coordinates for every UTM location
for lat, long in zip(gps_lat, gps_long):
    f_lat = float(lat)
    f_long = float(long)
# returns a tuple with the form (LATITUDE,LONGITUDE)
    gps_coordinates.append(utm.to_latlon(f_lat, f_long, 30, 'N'))
    
# add the newly obtained GPS coordinates to the dataframe
dataframe_filtered['Coordinates_GPS'] = gps_coordinates

# split Coordinates_GPS in two columns
dataframe_filtered[['Latitude','Longitude']] = pd.DataFrame(dataframe_filtered['Coordinates_GPS'].tolist(),index=dataframe_filtered.index)

dataframe_filtered_GPS = dataframe_filtered
dataframe_filtered_GPS.head()


StreetType District PostalCode Section            StreetName  \
0         CL       08      39011     020      FAUSTINO CAVADAS   
1         CL       08      39012     007        COSTA QUEBRADA   
2         CL       08      39012     012         INES D. NOVAL   
3         CL       08      39012     012         INES D. NOVAL   
4         CL       07      39006     012  FERNANDO DE LOS RIOS   

           Lat_UTM          Long_UTM  \
0  430592.56000000  4810310.05000000   
1  429633.68000000  4813410.42000000   
2  434920.66000000  4814743.53000000   
3  434890.16000000  4814688.66000000   
4  435178.29000000  4813424.31000000   

                             Coordinates_GPS   Latitude  Longitude  
0  (43.442475049099215, -3.8577163390893805)  43.442475  -3.857716  
1   (43.47029921592573, -3.8699646672425647)  43.470299  -3.869965  
2    (43.4827804017062, -3.8047656625950004)  43.482780  -3.804766  
3  (43.482283728116016, -3.8051362254977525)  43.482284  -3.805136  
4  (43.470925241101796, -3.8014231395857867)  43.470925  -3.801423

In [12]:
dataframe_filtered_GPS.shape

(970, 10)

In [13]:
# drop no longer needed UTM coordinates 
dataframe_filtered_GPS.drop(['Lat_UTM','Long_UTM'], axis = 1, inplace=True)
dataframe_filtered_GPS.head()

StreetType District PostalCode Section            StreetName  \
0         CL       08      39011     020      FAUSTINO CAVADAS   
1         CL       08      39012     007        COSTA QUEBRADA   
2         CL       08      39012     012         INES D. NOVAL   
3         CL       08      39012     012         INES D. NOVAL   
4         CL       07      39006     012  FERNANDO DE LOS RIOS   

                             Coordinates_GPS   Latitude  Longitude  
0  (43.442475049099215, -3.8577163390893805)  43.442475  -3.857716  
1   (43.47029921592573, -3.8699646672425647)  43.470299  -3.869965  
2    (43.4827804017062, -3.8047656625950004)  43.482780  -3.804766  
3  (43.482283728116016, -3.8051362254977525)  43.482284  -3.805136  
4  (43.470925241101796, -3.8014231395857867)  43.470925  -3.801423

In [14]:
dataframe_filtered_GPS.shape

(970, 8)

In [15]:
# drop no longer needed Coordinates_GPS tuple column
dataframe_filtered_GPS.drop(['Coordinates_GPS'], axis = 1, inplace=True)
dataframe_filtered_GPS.shape

(970, 7)

In [16]:
dataframe_filtered_GPS.head()

StreetType District PostalCode Section            StreetName   Latitude  \
0         CL       08      39011     020      FAUSTINO CAVADAS  43.442475   
1         CL       08      39012     007        COSTA QUEBRADA  43.470299   
2         CL       08      39012     012         INES D. NOVAL  43.482780   
3         CL       08      39012     012         INES D. NOVAL  43.482284   
4         CL       07      39006     012  FERNANDO DE LOS RIOS  43.470925   

   Longitude  
0  -3.857716  
1  -3.869965  
2  -3.804766  
3  -3.805136  
4  -3.801423

In [17]:
# Now we have the Santander dataframe with all the relevant data in the desired format
df_santander = dataframe_filtered_GPS

print('The Santander dataframe has {} districts and {} postal codes.'.format(
        len(df_santander['District'].unique()),
        len(df_santander['PostalCode'].unique()),
    )
)

The Santander dataframe has 8 districts and 13 postal codes.


#### Begin to prepare filtered dataframes

To explore the postal codes present in the dataframe

In [18]:
df_aux1 = df_santander['PostalCode'].unique()
df_aux1.sort()
print(df_aux1)

['36005' '39001' '39002' '39003' '39004' '39005' '39006' '39007' '39008'
 '39009' '39010' '39011' '39012']


Now, we remove postal code 36005, for being an anomaly

In [19]:
df_santander_f1 = df_santander.drop(df_santander[df_santander.PostalCode == '36005'].index)

Then, let's order the resulting postal codes, to know first and last

In [20]:
df_aux2 = df_santander_f1['PostalCode'].unique()
df_aux2.sort()
print(df_aux2)

['39001' '39002' '39003' '39004' '39005' '39006' '39007' '39008' '39009'
 '39010' '39011' '39012']


In [21]:
df_santander_f1.shape

(969, 7)

Remove all rows not belonging to first or last postal code (39001,39012)

In [22]:
df_santander_f2 = df_santander_f1.drop(df_santander_f1[ (df_santander_f1['PostalCode'] != '39001') & (df_santander_f1['PostalCode'] != '39012') ].index) 
df_aux2 = df_santander_f2['PostalCode'].unique()
df_aux2.sort()
print(df_aux2)

['39001' '39012']


In [23]:
df_santander_f2.groupby('PostalCode').count()

StreetType  District  Section  StreetName  Latitude  Longitude
PostalCode                                                                
39001               34        34       34          34        34         34
39012              322       322      322         322       322        322

In [24]:
df_santander_filtered = df_santander_f2

In [25]:
df_santander_filtered.shape

(356, 7)

To check duplicate streets

In [26]:
df_santander_filtered.groupby('StreetName').count()

StreetType  District  PostalCode  Section  \
StreetName                                                                   
ALBERICIA                                 3         3           3        3   
ALFONSINA STORNI                          1         1           1        1   
ALSEDO BUSTAMANTE                         1         1           1        1   
ARCILLERO                                 1         1           1        1   
ARRIBA                                    2         2           2        2   
ARSENIO ODRIOZOLA                         2         2           2        2   
ASILO                                     2         2           2        2   
ATALAYA                                   2         2           2        2   
AURELIO RUIZ CRESPO                       1         1           1        1   
AUTONOMIA                                 5         5           5        5   
AVIADOR JUAN IGNACIO POMBO                2         2           2        2   
AVIADORES CANTABROS                       1         1           1        1   
AVICHE                                    5         5           5        5   
BELLAVISTA                                6         6           6        6   
BOLADO                                    4         4           4        4   
CALERUCO                                  2         2           2        2   
CALVARIO                                  3         3           3        3   
CAMUS                                     9         9           9        9   
CANTABRIA                                15        15          15       15   
CANTO CERCADO                             1         1           1        1   
CASTOR AGRA GARCIA                        1         1           1        1   
CERVANTES                                 2         2           2        2   
CLARA CAMPOAMOR                           1         1           1        1   
CONCHA ESPINA                             1         1           1        1   
CONSUELO BERGES                           3         3           3        3   
COOPERATIVA DEL CAMPO                     1         1           1        1   
CORBAN                                    2         2           2        2   
CORBANERA                                14        14          14       14   
CORCEÑO                                   4         4           4        4   
CORCONERAS                                2         2           2        2   
COSTA QUEBRADA                            1         1           1        1   
CUETO                                     2         2           2        2   
DOCTOR DIEGO MADRAZO                      4         4           4        4   
DOCTOR GONZALEZ TORRE                     1         1           1        1   
EDUARDO OBREGON BARREDA                   1         1           1        1   
EL CAMPIZO                                2         2           2        2   
EL INGENIO                                1         1           1        1   
EL MIRADOR                                1         1           1        1   
EL RECIAL                                 3         3           3        3   
EL SOMO                                   5         5           5        5   
ELENA QUIROGA                             1         1           1        1   
ERNEST LLUCH                              2         2           2        2   
FLORIDA                                   1         1           1        1   
FRANCISCO DE CACERES                      2         2           2        2   
FUMORIL                                   8         8           8        8   
GUEVARA                                   4         4           4        4   
HERMANOS TONETTI                          4         4           4        4   
INES D. NOVAL                            16        16          16       16   
JESUS OTERO                               3         3           3        3   
JORGE SEPULVEDA                           1         1  

Remove duplicates, because we take just the first occurrence of each street

In [27]:
df_santander_filtered_unique = df_santander_filtered.drop_duplicates(subset=['StreetName'], keep='first')

In [28]:
df_santander_filtered_unique.reset_index(drop=True,inplace=True)
df_santander_filtered_unique

StreetType District PostalCode Section                       StreetName  \
0           CL       08      39012     007                   COSTA QUEBRADA   
1           CL       08      39012     012                    INES D. NOVAL   
2           CL       08      39012     007                           CORBAN   
3           CL       07      39012     020                         REPUENTE   
4           CL       07      39012     001                         PRONILLO   
5           CL       08      39012     008                           AVICHE   
6           CL       08      39012     024                          SOMONTE   
7           CL       08      39012     009                        CORBANERA   
8           CL       08      39012     024                    ELENA QUIROGA   
9           CL       08      39012     024                    MAZO DE ABAJO   
10          CL       08      39012     008                         LA TORRE   
11          CL       08      39012     011                          FUMORIL   
12          CL       08      39012     009                         TRISTANA   
13          CL       08      39012     010                           ARRIBA   
14          AV       08      39012     027             DOCTOR DIEGO MADRAZO   
15          CL       01      39001     003                          GUEVARA   
16          CL       08      39012     011                      JESUS OTERO   
17          CL       08      39012     009                       SAN MIGUEL   
18          CL       03      39001     002                          LA LEVA   
19          CL       08      39012     011                            CAMUS   
20          CL       08      39012     024                  MANUEL CACICEDO   
21          CL       08      39012     007                          CORCEÑO   
22          CL       08      39012     008                SAN PEDRO DEL MAR   
23          CL       08      39012     024             VICTORIANO FERNANDEZ   
24          CL       08      39012     024                          EL SOMO   
25          CL       08      39012     022                  CONSUELO BERGES   
26          CL       08      39012     008                           BOLADO   
27          CL       08      39012     024                   MAZO DE ARRIBA   
28          BJ       07      39012     021                         SAN JUAN   
29          AV       07      39012     023                      LOS CASTROS   
30          CL       03      39001     003                   MARIA CRISTINA   
31          CL       08      39012     015                        LA TEJERA   
32          CL       07      39012     021                  JORGE SEPULVEDA   
33          CL       08      39012     008          EDUARDO OBREGON BARREDA   
34          CL       08      39012     016             FRANCISCO DE CACERES   
35          AV       08      39012     024                   VIRGEN DEL MAR   
36          CT       03      39001     002                          ATALAYA   
37          CL       08      39012     011                 HERMANOS TONETTI   
38          GR       07      39012     021    REPUENTE GRUPO FERNANDO ATECA   
39          CL       08      39012     010              MATILDE DE LA TORRE   
40          CL       08      39012     007                       LA CUEVONA   
41          CL       08      39012     011                       LA ROCHELA   
42          CL       08      39012     011                       CORCONERAS   
43          CL       08      39012     007                   SANTA CATALINA   
44          CL       08      39012     009                        LA HONDAL   
45          CL       08      39012     012                        LA PEREDA   
46          CL       07      39012     021               CASTOR AGRA GARCIA   
47          CL       08      39012     010           PEDRO RODRIGUEZ PARETS   
48          CL       08      39012     007         LAURO FERNANDEZ GONZALEZ   
49          CL       08      39012     015            

To check how many streets belong to each of the two postal codes in treatment

In [29]:
df_santander_filtered_unique.groupby('PostalCode').count()

StreetType  District  Section  StreetName  Latitude  Longitude
PostalCode                                                                
39001               21        21       21          21        21         21
39012               96        96       96          96        96         96

In [30]:
df_santander_filtered_unique.shape

(117, 7)

#### Final Santander dataframe with just 2 postal codes and no duplicates

In [31]:
# Santander DataFrame
sdf = df_santander_filtered_unique

In [32]:
sdf

StreetType District PostalCode Section                       StreetName  \
0           CL       08      39012     007                   COSTA QUEBRADA   
1           CL       08      39012     012                    INES D. NOVAL   
2           CL       08      39012     007                           CORBAN   
3           CL       07      39012     020                         REPUENTE   
4           CL       07      39012     001                         PRONILLO   
5           CL       08      39012     008                           AVICHE   
6           CL       08      39012     024                          SOMONTE   
7           CL       08      39012     009                        CORBANERA   
8           CL       08      39012     024                    ELENA QUIROGA   
9           CL       08      39012     024                    MAZO DE ABAJO   
10          CL       08      39012     008                         LA TORRE   
11          CL       08      39012     011                          FUMORIL   
12          CL       08      39012     009                         TRISTANA   
13          CL       08      39012     010                           ARRIBA   
14          AV       08      39012     027             DOCTOR DIEGO MADRAZO   
15          CL       01      39001     003                          GUEVARA   
16          CL       08      39012     011                      JESUS OTERO   
17          CL       08      39012     009                       SAN MIGUEL   
18          CL       03      39001     002                          LA LEVA   
19          CL       08      39012     011                            CAMUS   
20          CL       08      39012     024                  MANUEL CACICEDO   
21          CL       08      39012     007                          CORCEÑO   
22          CL       08      39012     008                SAN PEDRO DEL MAR   
23          CL       08      39012     024             VICTORIANO FERNANDEZ   
24          CL       08      39012     024                          EL SOMO   
25          CL       08      39012     022                  CONSUELO BERGES   
26          CL       08      39012     008                           BOLADO   
27          CL       08      39012     024                   MAZO DE ARRIBA   
28          BJ       07      39012     021                         SAN JUAN   
29          AV       07      39012     023                      LOS CASTROS   
30          CL       03      39001     003                   MARIA CRISTINA   
31          CL       08      39012     015                        LA TEJERA   
32          CL       07      39012     021                  JORGE SEPULVEDA   
33          CL       08      39012     008          EDUARDO OBREGON BARREDA   
34          CL       08      39012     016             FRANCISCO DE CACERES   
35          AV       08      39012     024                   VIRGEN DEL MAR   
36          CT       03      39001     002                          ATALAYA   
37          CL       08      39012     011                 HERMANOS TONETTI   
38          GR       07      39012     021    REPUENTE GRUPO FERNANDO ATECA   
39          CL       08      39012     010              MATILDE DE LA TORRE   
40          CL       08      39012     007                       LA CUEVONA   
41          CL       08      39012     011                       LA ROCHELA   
42          CL       08      39012     011                       CORCONERAS   
43          CL       08      39012     007                   SANTA CATALINA   
44          CL       08      39012     009                        LA HONDAL   
45          CL       08      39012     012                        LA PEREDA   
46          CL       07      39012     021               CASTOR AGRA GARCIA   
47          CL       08      39012     010           PEDRO RODRIGUEZ PARETS   
48          CL       08      39012     007         LAURO FERNANDEZ GONZALEZ   
49          CL       08      39012     015            

#### Plot the data on maps

In [33]:
address = 'Santander, ES'

geolocator = Nominatim(user_agent="santander_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of the city of Santander are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of the city of Santander are 43.4620412, -3.8099719.


Create a map of Santander with streets superimposed on top, each one with its district and postal code.

In [34]:
# create map of Santander using latitude and longitude values
map_santander = folium.Map(location=[latitude, longitude], zoom_start=13)

# add markers to map
for street, lat, long, district, postalcode in zip(sdf['StreetName'], sdf['Latitude'], 
                                                   sdf['Longitude'], sdf['District'], 
                                                   sdf['PostalCode']):
    label = '{} ({}, {})'.format(street, district, postalcode)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, long],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_santander)
    
map_santander

In [35]:
sdf.shape

(117, 7)

Now, we create a map of Santander with streets superimposed on top, but differentiating by postal code

In [36]:
# # Dataframe of Postal Code 39001 alone
sdf_39001 = sdf.drop(sdf[ (sdf['PostalCode'] != '39001') ].index) 
sdf_39001 

StreetType District PostalCode Section           StreetName   Latitude  \
15          CL       01      39001     003              GUEVARA  43.465550   
18          CL       03      39001     002              LA LEVA  43.467443   
30          CL       03      39001     003       MARIA CRISTINA  43.468321   
36          CT       03      39001     002              ATALAYA  43.467079   
51          CL       02      39001     021           JUAN XXIII  43.466040   
53          CL       03      39001     002        SAN CELEDONIO  43.466660   
72          CL       03      39001     007       RIO DE LA PILA  43.468416   
76          CL       01      39001     002             SAN JOSE  43.464434   
77          CL       03      39001     004    ALSEDO BUSTAMANTE  43.465899   
81          CL       02      39001     021         VIA CORNELIA  43.467975   
82          CL       03      39001     003  AURELIO RUIZ CRESPO  43.467886   
92          CL       03      39001     002         VISTA ALEGRE  43.467215   
95          CL       03      39001     002                ASILO  43.466012   
96          CL       01      39001     004             RUALASAL  43.464759   
98          PJ       01      39001     002            ARCILLERO  43.464416   
108         CL       03      39001     005        OBISPO PUCHOL  43.467200   
109         CL       01      39001     006            CERVANTES  43.466087   
112         CL       01      39001     003              SEVILLA  43.465357   
113         CL       02      39001     020            LOS CAÑOS  43.466818   
115         CL       03      39001     008      PRADO SAN ROQUE  43.468491   
116         CL       01      39001     007              FLORIDA  43.464656   

     Longitude  
15   -3.804091  
18   -3.807361  
30   -3.806775  
36   -3.806902  
51   -3.812874  
53   -3.807685  
72   -3.804033  
76   -3.804180  
77   -3.805460  
81   -3.810516  
82   -3.804864  
92   -3.808073  
95   -3.808504  
96   -3.805086  
98   -3.805333  
108  -3.804880  
109  -3.809841  
112  -3.805010  
113  -3.811706  
115  -3.800173  
116  -3.812394

In [37]:
# Remove duplicate streets to better compare in the following map
sdf_39001_unique = sdf_39001.drop_duplicates(subset=['StreetName'], keep='first').reset_index(drop=True)
sdf_39001_unique.shape

(21, 7)

In [38]:
# Dataframe of Postal Code 39012 alone
sdf_39012 = sdf.drop(sdf[ (sdf['PostalCode'] != '39012') ].index) 
sdf_39012 

StreetType District PostalCode Section                       StreetName  \
0           CL       08      39012     007                   COSTA QUEBRADA   
1           CL       08      39012     012                    INES D. NOVAL   
2           CL       08      39012     007                           CORBAN   
3           CL       07      39012     020                         REPUENTE   
4           CL       07      39012     001                         PRONILLO   
5           CL       08      39012     008                           AVICHE   
6           CL       08      39012     024                          SOMONTE   
7           CL       08      39012     009                        CORBANERA   
8           CL       08      39012     024                    ELENA QUIROGA   
9           CL       08      39012     024                    MAZO DE ABAJO   
10          CL       08      39012     008                         LA TORRE   
11          CL       08      39012     011                          FUMORIL   
12          CL       08      39012     009                         TRISTANA   
13          CL       08      39012     010                           ARRIBA   
14          AV       08      39012     027             DOCTOR DIEGO MADRAZO   
16          CL       08      39012     011                      JESUS OTERO   
17          CL       08      39012     009                       SAN MIGUEL   
19          CL       08      39012     011                            CAMUS   
20          CL       08      39012     024                  MANUEL CACICEDO   
21          CL       08      39012     007                          CORCEÑO   
22          CL       08      39012     008                SAN PEDRO DEL MAR   
23          CL       08      39012     024             VICTORIANO FERNANDEZ   
24          CL       08      39012     024                          EL SOMO   
25          CL       08      39012     022                  CONSUELO BERGES   
26          CL       08      39012     008                           BOLADO   
27          CL       08      39012     024                   MAZO DE ARRIBA   
28          BJ       07      39012     021                         SAN JUAN   
29          AV       07      39012     023                      LOS CASTROS   
31          CL       08      39012     015                        LA TEJERA   
32          CL       07      39012     021                  JORGE SEPULVEDA   
33          CL       08      39012     008          EDUARDO OBREGON BARREDA   
34          CL       08      39012     016             FRANCISCO DE CACERES   
35          AV       08      39012     024                   VIRGEN DEL MAR   
37          CL       08      39012     011                 HERMANOS TONETTI   
38          GR       07      39012     021    REPUENTE GRUPO FERNANDO ATECA   
39          CL       08      39012     010              MATILDE DE LA TORRE   
40          CL       08      39012     007                       LA CUEVONA   
41          CL       08      39012     011                       LA ROCHELA   
42          CL       08      39012     011                       CORCONERAS   
43          CL       08      39012     007                   SANTA CATALINA   
44          CL       08      39012     009                        LA HONDAL   
45          CL       08      39012     012                        LA PEREDA   
46          CL       07      39012     021               CASTOR AGRA GARCIA   
47          CL       08      39012     010           PEDRO RODRIGUEZ PARETS   
48          CL       08      39012     007         LAURO FERNANDEZ GONZALEZ   
49          CL       08      39012     015                   LOS PORTUARIOS   
50          CL       08      39012     015                        ALBERICIA   
52          CL       08      39012     007                       EL MIRADOR   
54          CL       08      39012     024                   JUAN JOSE MIER   
55          CL       08      39012     007       AVIAD

In [39]:
# Remove duplicate streets to better compare in the following map
sdf_39012_unique = sdf_39012.drop_duplicates(subset=['StreetName'], keep='first').reset_index(drop=True)
sdf_39012_unique.shape

(96, 7)

First, we plot 39001 streets on a new map

In [40]:
# create map of Santander using latitude and longitude values
map_santander2 = folium.Map(location=[latitude, longitude], zoom_start=13)

# add markers to map for dataframe with 39001 streets
for street, lat, long, district, postalcode in zip(sdf_39001_unique['StreetName'], sdf_39001_unique['Latitude'], 
                                                   sdf_39001_unique['Longitude'], sdf_39001_unique['District'], 
                                                   sdf_39001_unique['PostalCode']):
    label = '{} ({}, {})'.format(street, district, postalcode)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, long],
        radius=5,
        popup=label,
        color='green',
        fill=True,
        fill_color='#62cc31',
        fill_opacity=0.7,
        parse_html=False).add_to(map_santander2)
    
map_santander2

Then, we plot 39012 streets on a new map

In [41]:
# add markers to map for dataframe with 39001 streets
for street, lat, long, district, postalcode in zip(sdf_39012_unique['StreetName'], sdf_39012_unique['Latitude'], 
                                                   sdf_39012_unique['Longitude'], sdf_39012_unique['District'], 
                                                   sdf_39012_unique['PostalCode']):
    label = '{} ({}, {})'.format(street, district, postalcode)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, long],
        radius=5,
        popup=label,
        color='red',
        fill=True,
        fill_color='#FF0000',
        fill_opacity=0.7,
        parse_html=False).add_to(map_santander2)
    
map_santander2

So we have green for 39001 streets and red for 39012 streets.

#### Next, we are going to start utilizing the Foursquare API to explore the streets and segment them

In [42]:
CLIENT_ID = 'XL5WFC051BLGJ4QOTZBYUUIGRFDJPHQ2CS3VGYQEHFMRWFFB' # your Foursquare ID
CLIENT_SECRET = 'IRU1QPBYKJGRZZ3XVNCIXMLOA3LMIKMXMEU3BHMVDRQKNF1N' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: XL5WFC051BLGJ4QOTZBYUUIGRFDJPHQ2CS3VGYQEHFMRWFFB
CLIENT_SECRET:IRU1QPBYKJGRZZ3XVNCIXMLOA3LMIKMXMEU3BHMVDRQKNF1N


Let's explore the first street in our dataframe

Get the street's name.

In [43]:
sdf.loc[0, 'StreetName']

'COSTA QUEBRADA'

In [44]:
street_latitude = sdf.loc[0, 'Latitude'] # neighborhood latitude value
street_longitude = sdf.loc[0, 'Longitude'] # neighborhood longitude value

street_name = sdf.loc[0, 'StreetName'] # neighborhood name

print('Latitude and longitude values of {} are {}, {}.'.format(street_name, 
                                                               street_latitude, 
                                                               street_longitude))

Latitude and longitude values of COSTA QUEBRADA are 43.47029921592573, -3.8699646672425647.


To get venues for the first street of the dataframe

In [45]:
LIMIT = 100 # limit of number of venues returned by Foursquare API

radius = 500 # define radius

# create URL
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    street_latitude, 
    street_longitude, 
    radius, 
    LIMIT)
url # display URL

'https://api.foursquare.com/v2/venues/explore?&client_id=XL5WFC051BLGJ4QOTZBYUUIGRFDJPHQ2CS3VGYQEHFMRWFFB&client_secret=IRU1QPBYKJGRZZ3XVNCIXMLOA3LMIKMXMEU3BHMVDRQKNF1N&v=20180605&ll=43.47029921592573,-3.8699646672425647&radius=500&limit=100'

In [46]:
results = requests.get(url).json()
results


{'meta': {'code': 200, 'requestId': '5ea9c8e214a1267c9ca13caf'},
 'response': {'headerLocation': 'Soto de la Marina',
  'headerFullLocation': 'Soto de la Marina',
  'headerLocationGranularity': 'city',
  'totalResults': 4,
  'suggestedBounds': {'ne': {'lat': 43.47479922042573,
    'lng': -3.86377559463083},
   'sw': {'lat': 43.465799211425725, 'lng': -3.8761537398542996}},
  'groups': [{'type': 'Recommended Places',
    'name': 'recommended',
    'items': [{'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4c863eb52f1c236ac23c5b43',
       'name': 'El Llar',
       'location': {'lat': 43.4661330769018,
        'lng': -3.8708171856596785,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.4661330769018,
          'lng': -3.8708171856596785}],
        'distance': 468,
        'cc': 'ES',
        'country': 'España',
        'formattedAddress'

We know that all the information is in the items key. Now, let's borrow the get_category_type function from the Foursquare lab.

In [47]:
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

Now we are ready to clean the json and structure it into a pandas dataframe.

In [48]:
venues = results['response']['groups'][0]['items']
    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

nearby_venues.head()

name          categories        lat       lng
0                  El Llar  Spanish Restaurant  43.466133 -3.870817
1              Casa Miguel  Spanish Restaurant  43.466709 -3.868025
2  Restaurante Casa Miguel  Spanish Restaurant  43.467554 -3.872010
3          El Llar Terraza                 Pub  43.466329 -3.870943

And how many venues were returned by Foursquare? 

In [49]:
print('{} venues were returned by Foursquare.'.format(nearby_venues.shape[0]))

4 venues were returned by Foursquare.


In [50]:
sdf.head()

StreetType District PostalCode Section      StreetName   Latitude  Longitude
0         CL       08      39012     007  COSTA QUEBRADA  43.470299  -3.869965
1         CL       08      39012     012   INES D. NOVAL  43.482780  -3.804766
2         CL       08      39012     007          CORBAN  43.467523  -3.870217
3         CL       07      39012     020        REPUENTE  43.465691  -3.834289
4         CL       07      39012     001        PRONILLO  43.464794  -3.830979

Let's create a function to repeat the same process to all the neighborhoods in our dataframe

In [51]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for i, name, lat, lng in zip(sdf.index, names, latitudes, longitudes):
        print(i, name, lat, lng)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Street', 
                  'Street Latitude', 
                  'Street Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [52]:
sdf_venues = getNearbyVenues(names=sdf['StreetName'],
                                   latitudes=sdf['Latitude'],
                                   longitudes=sdf['Longitude']
                                  )

0 COSTA QUEBRADA 43.47029921592573 -3.8699646672425647
1 INES D. NOVAL 43.4827804017062 -3.8047656625950004
2 CORBAN 43.46752343168151 -3.8702172330613376
3 REPUENTE 43.46569124599082 -3.834288618599536
4 PRONILLO 43.464794477934085 -3.8309787917538314
5 AVICHE 43.47400132304138 -3.8225048599030576
6 SOMONTE 43.47057652735494 -3.859825362324643
7 CORBANERA 43.47786941190596 -3.8341612830904124
8 ELENA QUIROGA 43.46794284583219 -3.8648895519109225
9 MAZO DE ABAJO 43.47042717028424 -3.8610426415214008
10 LA TORRE 43.47528082309851 -3.8158705417663645
11 FUMORIL 43.48394842198416 -3.8087238553145037
12 TRISTANA 43.47291994327368 -3.829728243192483
13 ARRIBA 43.479822944740825 -3.8119278521899695
14 DOCTOR DIEGO MADRAZO 43.48477563021825 -3.794004841854865
15 GUEVARA 43.46555039455035 -3.8040906355932336
16 JESUS OTERO 43.48123073340663 -3.8108875583491573
17 SAN MIGUEL 43.47102909219792 -3.8382517145933024
18 LA LEVA 43.46744283213899 -3.807361437234898
19 CAMUS 43.48632584178901 -3.79812

Let's check how many venues were returned for each street

In [53]:
sdf_venues.head()

Street  Street Latitude  Street Longitude                    Venue  \
0  COSTA QUEBRADA        43.470299         -3.869965                  El Llar   
1  COSTA QUEBRADA        43.470299         -3.869965              Casa Miguel   
2  COSTA QUEBRADA        43.470299         -3.869965  Restaurante Casa Miguel   
3  COSTA QUEBRADA        43.470299         -3.869965          El Llar Terraza   
4   INES D. NOVAL        43.482780         -3.804766                Mercadona   

   Venue Latitude  Venue Longitude      Venue Category  
0       43.466133        -3.870817  Spanish Restaurant  
1       43.466709        -3.868025  Spanish Restaurant  
2       43.467554        -3.872010  Spanish Restaurant  
3       43.466329        -3.870943                 Pub  
4       43.481584        -3.800052         Supermarket

In [54]:
sdf_venues.shape

(1103, 7)

In [55]:
sdf_venues.groupby('Street').count()

Street Latitude  Street Longitude  Venue  \
Street                                                                      
ALBERICIA                                      5                 5      5   
ALFONSINA STORNI                               6                 6      6   
ALSEDO BUSTAMANTE                             66                66     66   
ARCILLERO                                     57                57     57   
ARRIBA                                         2                 2      2   
ARSENIO ODRIOZOLA                              8                 8      8   
ASILO                                         35                35     35   
ATALAYA                                       29                29     29   
AURELIO RUIZ CRESPO                           31                31     31   
AUTONOMIA                                      8                 8      8   
AVIADOR JUAN IGNACIO POMBO                     4                 4      4   
AVIADORES CANTABROS                            2                 2      2   
AVICHE                                         2                 2      2   
BELLAVISTA                                     4                 4      4   
BOLADO                                         1                 1      1   
CALERUCO                                      10                10     10   
CALVARIO                                       1                 1      1   
CAMUS                                          5                 5      5   
CANTABRIA                                     15                15     15   
CANTO CERCADO                                  4                 4      4   
CASTOR AGRA GARCIA                             2                 2      2   
CERVANTES                                     29                29     29   
CLARA CAMPOAMOR                                5                 5      5   
CONCHA ESPINA                                  8                 8      8   
CONSUELO BERGES                                4                 4      4   
COOPERATIVA DEL CAMPO                          1                 1      1   
CORBAN                                         4                 4      4   
CORBANERA                                      4                 4      4   
CORCEÑO                                        3                 3      3   
CORCONERAS                                     1                 1      1   
COSTA QUEBRADA                                 4                 4      4   
CUETO                                          3                 3      3   
DOCTOR DIEGO MADRAZO                          10                10     10   
DOCTOR GONZALEZ TORRE                          1                 1      1   
EDUARDO OBREGON BARREDA                        2                 2      2   
EL CAMPIZO                                     4                 4      4   
EL INGENIO                                    17                17     17   
EL MIRADOR                                     1                 1      1   
EL RECIAL                                      4                 4      4   
EL SOMO                                        4                 4      4   
ELENA QUIROGA                                  4                 4      4   
ERNEST LLUCH                                   4                 4      4   
FLORIDA                                       23                23     23   
FRANCISCO DE CACERES                          14                14     14   
FUMORIL                                        1                 1      1   
GUEVARA                                       50                50     50   
HERMANOS TONETTI                               1                 1      1   
INES D. NOVAL                                  4                 4      4   
JESUS OTERO                                    2                 2      2   
JORGE SEPULVEDA                                3                 3      3   
JOSE MARIA GONZALEZ TREVILLA 

Let's find out how many unique categories can be curated from all the returned venues

In [56]:
print('There are {} unique categories.'.format(len(sdf_venues['Venue Category'].unique())))

There are 74 unique categories.


#### Analyze Each Neighborhood

In [57]:
# one hot encoding
sdf_onehot = pd.get_dummies(sdf_venues[['Venue Category']], prefix="", prefix_sep="")

# add street column back to dataframe
sdf_onehot['Street'] = sdf_venues['Street'] 

# move street column to the first column
street_df = sdf_onehot['Street']
sdf_onehot.drop(labels=['Street'], axis=1,inplace = True)
sdf_onehot.insert(0, 'Street', street_df)

sdf_onehot.head()

Street  Art Gallery  Arts & Crafts Store  Athletics & Sports  \
0  COSTA QUEBRADA            0                    0                   0   
1  COSTA QUEBRADA            0                    0                   0   
2  COSTA QUEBRADA            0                    0                   0   
3  COSTA QUEBRADA            0                    0                   0   
4   INES D. NOVAL            0                    0                   0   

   BBQ Joint  Bakery  Bar  Beach  Beer Bar  Big Box Store  \
0          0       0    0      0         0              0   
1          0       0    0      0         0              0   
2          0       0    0      0         0              0   
3          0       0    0      0         0              0   
4          0       0    0      0         0              0   

   Bike Rental / Bike Share  Bookstore  Boutique  Breakfast Spot  Brewery  \
0                         0          0         0               0        0   
1                         0          0         0               0        0   
2                         0          0         0               0        0   
3                         0          0         0               0        0   
4                         0          0         0               0        0   

   Building  Burger Joint  Café  Campground  Castle  Church  Clothing Store  \
0         0             0     0           0       0       0               0   
1         0             0     0           0       0       0               0   
2         0             0     0           0       0       0               0   
3         0             0     0           0       0       0               0   
4         0             0     0           0       0       0               0   

   Cocktail Bar  Coffee Shop  Concert Hall  Convenience Store  \
0             0            0             0                  0   
1             0            0             0                  0   
2             0            0             0                  0   
3             0            0             0                  0   
4             0            0             0                  0   

   Convention Center  Department Store  Dessert Shop  Diner  \
0                  0                 0             0      0   
1                  0                 0             0      0   
2                  0                 0             0      0   
3                  0                 0             0      0   
4                  0                 0             0      0   

   Electronics Store  Fast Food Restaurant  Food & Drink Shop  Food Court  \
0                  0                     0                  0           0   
1                  0                     0                  0           0   
2                  0                     0                  0           0   
3                  0                     0                  0           0   
4                  0                     0                  0           0   

   Football Stadium  Frozen Yogurt Shop  Garden  Gastropub  Grocery Store  \
0                 0                   0       0          0              0   
1                 0                   0       0          0              0   
2                 0                   0       0          0              0   
3                 0                   0       0          0              0   
4                 0                   0       0          0              0   

   Gym  Gym / Fitness Center  Historic Site  History Museum  Hostel  Hotel  \
0    0                     0              0               0       0      0   
1    0                     0              0               0       0      0   
2    0                     0              0               0       0      0   
3    0                     0              0               0       0      0   
4    0                     0              0               0       0      0   

   Ice Cream Shop  Italian Restaurant  Light Rail Station  Lighthouse  \
0               0

And let's examine the new dataframe size.

In [58]:
sdf_onehot.shape

(1103, 75)

Next, let's group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

In [59]:
sdf_grouped = sdf_onehot.groupby('Street').mean().reset_index()
sdf_grouped

Street  Art Gallery  Arts & Crafts Store  \
0                          ALBERICIA     0.000000             0.000000   
1                   ALFONSINA STORNI     0.000000             0.000000   
2                  ALSEDO BUSTAMANTE     0.000000             0.000000   
3                          ARCILLERO     0.000000             0.000000   
4                             ARRIBA     0.000000             0.000000   
5                  ARSENIO ODRIOZOLA     0.000000             0.000000   
6                              ASILO     0.000000             0.000000   
7                            ATALAYA     0.000000             0.000000   
8                AURELIO RUIZ CRESPO     0.000000             0.000000   
9                          AUTONOMIA     0.000000             0.000000   
10        AVIADOR JUAN IGNACIO POMBO     0.000000             0.000000   
11               AVIADORES CANTABROS     0.000000             0.000000   
12                            AVICHE     0.000000             0.000000   
13                        BELLAVISTA     0.000000             0.000000   
14                            BOLADO     0.000000             0.000000   
15                          CALERUCO     0.000000             0.000000   
16                          CALVARIO     0.000000             0.000000   
17                             CAMUS     0.000000             0.000000   
18                         CANTABRIA     0.000000             0.000000   
19                     CANTO CERCADO     0.000000             0.000000   
20                CASTOR AGRA GARCIA     0.000000             0.000000   
21                         CERVANTES     0.034483             0.000000   
22                   CLARA CAMPOAMOR     0.000000             0.000000   
23                     CONCHA ESPINA     0.000000             0.000000   
24                   CONSUELO BERGES     0.000000             0.000000   
25             COOPERATIVA DEL CAMPO     0.000000             0.000000   
26                            CORBAN     0.000000             0.000000   
27                         CORBANERA     0.000000             0.000000   
28                           CORCEÑO     0.000000             0.333333   
29                        CORCONERAS     0.000000             0.000000   
30                    COSTA QUEBRADA     0.000000             0.000000   
31                             CUETO     0.000000             0.000000   
32              DOCTOR DIEGO MADRAZO     0.000000             0.000000   
33             DOCTOR GONZALEZ TORRE     0.000000             0.000000   
34           EDUARDO OBREGON BARREDA     0.000000             0.000000   
35                        EL CAMPIZO     0.000000             0.250000   
36                        EL INGENIO     0.000000             0.000000   
37                        EL MIRADOR     0.000000             0.000000   
38                         EL RECIAL     0.000000             0.000000   
39                           EL SOMO     0.000000             0.000000   
40                     ELENA QUIROGA     0.000000             0.000000   
41                      ERNEST LLUCH     0.000000             0.000000   
42                           FLORIDA     0.043478             0.000000   
43              FRANCISCO DE CACERES     0.000000             0.000000   
44                           FUMORIL     0.000000             0.000000   
45                           GUEVARA     0.000000             0.000000   
46                  HERMANOS TONETTI     0.000000             0.000000   
47                     INES D. NOVAL     0.000000             0.000000   
48                       JESUS OTERO     0.000000             0.000000   
49                   JORGE SEPULVEDA     0.000000             0.000000   
50      JOSE MARIA GONZALEZ TREVILLA     0.000000             0.000000   
51                    JUAN JOSE MIER     0.000000             0.000000   
52                        JUAN XXIII     0.076923             0.000000   
53                         LA CAND

And let's examine also the size of this dataframe.

In [60]:
sdf_grouped.shape

(117, 75)

Let's print each street along with the top 5 most common venue

In [61]:
num_top_venues = 5

for st in sdf_grouped['Street']:
    print("----"+st+"----")
    temp = sdf_grouped[sdf_grouped['Street'] == st].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----ALBERICIA----
               venue  freq
0         Restaurant   0.2
1        Supermarket   0.2
2      Big Box Store   0.2
3  Food & Drink Shop   0.2
4        Pizza Place   0.2


----ALFONSINA STORNI----
         venue  freq
0         Park  0.17
1       Bakery  0.17
2        Hotel  0.17
3  Supermarket  0.17
4      Stadium  0.17


----ALSEDO BUSTAMANTE----
                venue  freq
0  Spanish Restaurant  0.12
1                 Bar  0.11
2                Café  0.09
3    Tapas Restaurant  0.09
4           Nightclub  0.05


----ARCILLERO----
                venue  freq
0                 Bar  0.12
1                Café  0.12
2    Tapas Restaurant  0.09
3  Spanish Restaurant  0.07
4          Restaurant  0.07


----ARRIBA----
                venue  freq
0  Italian Restaurant   0.5
1  Spanish Restaurant   0.5
2         Art Gallery   0.0
3          Lighthouse   0.0
4            Pharmacy   0.0


----ARSENIO ODRIOZOLA----
                venue  freq
0          Restaurant  0.12
1  Spanish Res

4  Mediterranean Restaurant  0.00


----LA CUEVONA----
                venue  freq
0  Spanish Restaurant  0.67
1                 Pub  0.33
2         Art Gallery  0.00
3          Lighthouse  0.00
4                Park  0.00


----LA GLORIA----
                      venue  freq
0               Coffee Shop  0.25
1                  Boutique  0.25
2          Football Stadium  0.25
3  Bike Rental / Bike Share  0.25
4               Pizza Place  0.00


----LA HONDAL----
               venue  freq
0        Supermarket   0.4
1         Restaurant   0.2
2  Food & Drink Shop   0.2
3        Pizza Place   0.2
4        Art Gallery   0.0


----LA LEVA----
                venue  freq
0                Café  0.24
1    Tapas Restaurant  0.12
2  Spanish Restaurant  0.12
3          Restaurant  0.06
4        Burger Joint  0.06


----LA LLANILLA----
                      venue  freq
0                Restaurant  0.33
1                    Bakery  0.33
2                Playground  0.33
3               Art Gallery

              venue  freq
0              Café  0.21
1               Bar  0.16
2  Tapas Restaurant  0.11
3        Restaurant  0.05
4      Concert Hall  0.05




Let's put it into a new dataframe

First, let's write a function to sort the venues in descending order.

In [62]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

Now let's create the new dataframe and display the top 10 venues for each street.

In [63]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Street']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
streets_venues_sorted = pd.DataFrame(columns=columns)
streets_venues_sorted['Street'] = sdf_grouped['Street']

for ind in np.arange(sdf_grouped.shape[0]):
    streets_venues_sorted.iloc[ind, 1:] = return_most_common_venues(sdf_grouped.iloc[ind, :], num_top_venues)

streets_venues_sorted.head()

Street 1st Most Common Venue 2nd Most Common Venue  \
0          ALBERICIA           Pizza Place           Supermarket   
1   ALFONSINA STORNI                  Park    Seafood Restaurant   
2  ALSEDO BUSTAMANTE    Spanish Restaurant                   Bar   
3          ARCILLERO                  Café                   Bar   
4             ARRIBA    Spanish Restaurant    Italian Restaurant   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
0            Restaurant         Big Box Store     Food & Drink Shop   
1           Supermarket               Stadium                Bakery   
2                  Café      Tapas Restaurant             Nightclub   
3      Tapas Restaurant            Restaurant    Spanish Restaurant   
4              Wine Bar        Clothing Store          Cocktail Bar   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
0  Fast Food Restaurant     Electronics Store                 Diner   
1                 Hotel                Castle                Church   
2                 Plaza          Cocktail Bar                Bakery   
3                 Plaza        Ice Cream Shop              Wine Bar   
4           Coffee Shop          Concert Hall     Convenience Store   

  9th Most Common Venue 10th Most Common Venue  
0          Dessert Shop       Department Store  
1        Clothing Store           Cocktail Bar  
2    Frozen Yogurt Shop             Restaurant  
3           Coffee Shop      Convention Center  
4     Convention Center       Department Store

In [64]:
sdf_grouped.shape

(117, 75)

In [65]:
streets_venues_sorted.shape

(117, 11)

In [66]:
streets_venues_sorted

Street     1st Most Common Venue  \
0                          ALBERICIA               Pizza Place   
1                   ALFONSINA STORNI                      Park   
2                  ALSEDO BUSTAMANTE        Spanish Restaurant   
3                          ARCILLERO                      Café   
4                             ARRIBA        Spanish Restaurant   
5                  ARSENIO ODRIOZOLA                Campground   
6                              ASILO                      Café   
7                            ATALAYA                      Café   
8                AURELIO RUIZ CRESPO                       Bar   
9                          AUTONOMIA        Seafood Restaurant   
10        AVIADOR JUAN IGNACIO POMBO            Clothing Store   
11               AVIADORES CANTABROS        Athletics & Sports   
12                            AVICHE        Spanish Restaurant   
13                        BELLAVISTA               Snack Place   
14                            BOLADO                    Hostel   
15                          CALERUCO        Spanish Restaurant   
16                          CALVARIO                      Park   
17                             CAMUS                Campground   
18                         CANTABRIA                      Park   
19                     CANTO CERCADO        Spanish Restaurant   
20                CASTOR AGRA GARCIA        Spanish Restaurant   
21                         CERVANTES                      Café   
22                   CLARA CAMPOAMOR        Spanish Restaurant   
23                     CONCHA ESPINA                      Café   
24                   CONSUELO BERGES               Snack Place   
25             COOPERATIVA DEL CAMPO          Tapas Restaurant   
26                            CORBAN        Spanish Restaurant   
27                         CORBANERA                Restaurant   
28                           CORCEÑO        Italian Restaurant   
29                        CORCONERAS                 Surf Spot   
30                    COSTA QUEBRADA        Spanish Restaurant   
31                             CUETO               Video Store   
32              DOCTOR DIEGO MADRAZO               Snack Place   
33             DOCTOR GONZALEZ TORRE        Spanish Restaurant   
34           EDUARDO OBREGON BARREDA        Italian Restaurant   
35                        EL CAMPIZO       Arts & Crafts Store   
36                        EL INGENIO                     Hotel   
37                        EL MIRADOR                Campground   
38                         EL RECIAL               Snack Place   
39                           EL SOMO        Spanish Restaurant   
40                     ELENA QUIROGA        Spanish Restaurant   
41                      ERNEST LLUCH        Spanish Restaurant   
42                           FLORIDA                      Café   
43              FRANCISCO DE CACERES        Seafood Restaurant   
44                           FUMORIL        Italian Restaurant   
45                           GUEVARA        Spanish Restaurant   
46                  HERMANOS TONETTI                      Park   
47                     INES D. NOVAL               Video Store   
48                       JESUS OTERO        Spanish Restaurant   
49                   JORGE SEPULVEDA      Fast Food Restaurant   
50      JOSE MARIA GONZALEZ TREVILLA               Supermarket   
51                    JUAN JOSE MIER        Spanish Restaurant   
52                        JUAN XXIII                       Bar   
53                         LA CANDIA        Spanish Restaurant   
54                        LA CUEVONA        Spanish Restaurant   
55                         LA GLORIA  Bike Rental / Bike Share   
56                         LA HONDAL               Supermarket   
57                           LA LEVA                      Café   
58                       LA LLANILLA                Playground   
59                          LA LLOSA               Supermarket   
60  

#### Cluster Streets

We'll make a three-clustering comparison, to analyze and find the optimal option, which'll be the one with the least streets belonging to the postal code 39012 in the same cluster as the streets of the 39001 postal code.

So we will implement three clustering options: 
    
    a) 2 clusters (provided we are comparing 2 sets of streets), 
    b) 5 clusters, as an intermediate solution and 
    c) 20 clusters, as a way of obtaining the least possible number of streets from postal code 39012 clustered with 39001          ones

First of all, we check the dataframes to join

In [67]:
print(sdf.shape , '<-- sdf shape, to test if dataframes to join have equal dimensions')
print(streets_venues_sorted.shape , '<-- streets venues, to test if dataframes to join have equal dimensions')

(117, 7) <-- sdf shape, to test if dataframes to join have equal dimensions
(117, 11) <-- streets venues, to test if dataframes to join have equal dimensions


We'll send both dataframes to excel to keep their reference.

In [68]:
# send both dataframes to excel
sdf.to_excel("sdf.xlsx")
streets_venues_sorted.to_excel("streets_venues_sorted.xlsx")

Now, we start the pure clustering process

#### Run k-means to cluster the neighborhood into 2 clusters.

In [69]:
# make a working copy to keep a reference of the original sorted dataframe
streets_venues_sorted2 = streets_venues_sorted.copy()

In [70]:
# set number of clusters
kclusters = 2

sdf_grouped_clustering2 = sdf_grouped.drop('Street', 1)

# run k-means clustering
kmeans2 = KMeans(n_clusters=kclusters, random_state=0).fit(sdf_grouped_clustering2)

# check cluster labels generated for each row in the dataframe
kmeans2.labels_[0:10] 

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

Let's create a new dataframe that includes the cluster as well as the top 10 venues for each street.

In [71]:
streets_venues_sorted2.insert(0, 'Cluster Labels', kmeans2.labels_)

sdf_merged2 = sdf

# merge Santander data in sdf with streets_venues_sorted to add latitude/longitude for each street
sdf_merged2 = sdf_merged2.join(streets_venues_sorted2.set_index('Street'), on='StreetName')

In [72]:
sdf_merged2

StreetType District PostalCode Section                       StreetName  \
0           CL       08      39012     007                   COSTA QUEBRADA   
1           CL       08      39012     012                    INES D. NOVAL   
2           CL       08      39012     007                           CORBAN   
3           CL       07      39012     020                         REPUENTE   
4           CL       07      39012     001                         PRONILLO   
5           CL       08      39012     008                           AVICHE   
6           CL       08      39012     024                          SOMONTE   
7           CL       08      39012     009                        CORBANERA   
8           CL       08      39012     024                    ELENA QUIROGA   
9           CL       08      39012     024                    MAZO DE ABAJO   
10          CL       08      39012     008                         LA TORRE   
11          CL       08      39012     011                          FUMORIL   
12          CL       08      39012     009                         TRISTANA   
13          CL       08      39012     010                           ARRIBA   
14          AV       08      39012     027             DOCTOR DIEGO MADRAZO   
15          CL       01      39001     003                          GUEVARA   
16          CL       08      39012     011                      JESUS OTERO   
17          CL       08      39012     009                       SAN MIGUEL   
18          CL       03      39001     002                          LA LEVA   
19          CL       08      39012     011                            CAMUS   
20          CL       08      39012     024                  MANUEL CACICEDO   
21          CL       08      39012     007                          CORCEÑO   
22          CL       08      39012     008                SAN PEDRO DEL MAR   
23          CL       08      39012     024             VICTORIANO FERNANDEZ   
24          CL       08      39012     024                          EL SOMO   
25          CL       08      39012     022                  CONSUELO BERGES   
26          CL       08      39012     008                           BOLADO   
27          CL       08      39012     024                   MAZO DE ARRIBA   
28          BJ       07      39012     021                         SAN JUAN   
29          AV       07      39012     023                      LOS CASTROS   
30          CL       03      39001     003                   MARIA CRISTINA   
31          CL       08      39012     015                        LA TEJERA   
32          CL       07      39012     021                  JORGE SEPULVEDA   
33          CL       08      39012     008          EDUARDO OBREGON BARREDA   
34          CL       08      39012     016             FRANCISCO DE CACERES   
35          AV       08      39012     024                   VIRGEN DEL MAR   
36          CT       03      39001     002                          ATALAYA   
37          CL       08      39012     011                 HERMANOS TONETTI   
38          GR       07      39012     021    REPUENTE GRUPO FERNANDO ATECA   
39          CL       08      39012     010              MATILDE DE LA TORRE   
40          CL       08      39012     007                       LA CUEVONA   
41          CL       08      39012     011                       LA ROCHELA   
42          CL       08      39012     011                       CORCONERAS   
43          CL       08      39012     007                   SANTA CATALINA   
44          CL       08      39012     009                        LA HONDAL   
45          CL       08      39012     012                        LA PEREDA   
46          CL       07      39012     021               CASTOR AGRA GARCIA   
47          CL       08      39012     010           PEDRO RODRIGUEZ PARETS   
48          CL       08      39012     007         LAURO FERNANDEZ GONZALEZ   
49          CL       08      39012     015            

Finally, let's visualize the resulting clusters

In [73]:
# create map
map_clusters_2 = folium.Map(location=[latitude, longitude], zoom_start=13)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(sdf_merged2['Latitude'], sdf_merged2['Longitude'], sdf_merged2['StreetName'], sdf_merged2['Cluster Labels']):
#   label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    label = folium.Popup(poi + ' Street ')
   
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters_2)
       
map_clusters_2

Cluster with all the streets belonging to postal code 39001 and several from 39012 (in this case,cluster 1)

In [74]:
sdf_cluster2 = sdf_merged2.drop(sdf_merged2[ (sdf_merged2['Cluster Labels'] != 1) ].index).reset_index(drop=True)
sdf_cluster2 

StreetType District PostalCode Section                       StreetName  \
0          CL       08      39012     012                    INES D. NOVAL   
1          CL       08      39012     024                          SOMONTE   
2          CL       08      39012     009                        CORBANERA   
3          CL       08      39012     024                    MAZO DE ABAJO   
4          CL       08      39012     008                         LA TORRE   
5          CL       08      39012     011                          FUMORIL   
6          AV       08      39012     027             DOCTOR DIEGO MADRAZO   
7          CL       01      39001     003                          GUEVARA   
8          CL       08      39012     009                       SAN MIGUEL   
9          CL       03      39001     002                          LA LEVA   
10         CL       08      39012     011                            CAMUS   
11         CL       08      39012     024                  MANUEL CACICEDO   
12         CL       08      39012     007                          CORCEÑO   
13         CL       08      39012     008                SAN PEDRO DEL MAR   
14         CL       08      39012     024             VICTORIANO FERNANDEZ   
15         CL       08      39012     022                  CONSUELO BERGES   
16         CL       08      39012     008                           BOLADO   
17         CL       08      39012     024                   MAZO DE ARRIBA   
18         CL       03      39001     003                   MARIA CRISTINA   
19         CL       08      39012     015                        LA TEJERA   
20         CL       08      39012     008          EDUARDO OBREGON BARREDA   
21         CL       08      39012     016             FRANCISCO DE CACERES   
22         CT       03      39001     002                          ATALAYA   
23         CL       08      39012     011                 HERMANOS TONETTI   
24         CL       08      39012     011                       LA ROCHELA   
25         CL       08      39012     011                       CORCONERAS   
26         CL       08      39012     009                        LA HONDAL   
27         CL       08      39012     012                        LA PEREDA   
28         CL       08      39012     010           PEDRO RODRIGUEZ PARETS   
29         CL       08      39012     007         LAURO FERNANDEZ GONZALEZ   
30         CL       08      39012     015                   LOS PORTUARIOS   
31         CL       08      39012     015                        ALBERICIA   
32         CL       02      39001     021                       JUAN XXIII   
33         CL       08      39012     007                       EL MIRADOR   
34         CL       03      39001     002                    SAN CELEDONIO   
35         CL       08      39012     007       AVIADOR JUAN IGNACIO POMBO   
36         CL       08      39012     027     JOSE MARIA GONZALEZ TREVILLA   
37         CL       08      39012     024                          ROSTRIO   
38         CL       08      39012     011                  RICARDO LORENZO   
39         CL       08      39012     019                        AUTONOMIA   
40         CL       08      39012     009                     LOS BARBAJOS   
41         CL       08      39012     005                  MIES DE MILLAJO   
42         CL       08      39012     012                       BELLAVISTA   
43         CL       08      39012     019                        VALDENOJA   
44         CL       08      39012     007                    LAS PORTILLAS   
45         AV       04      39012     014                        CANTABRIA   
46         CL       08      39012     008  RICARDO FERNANDEZ DE LA REGUERA   
47         CL       08      39012     007                      LA LLANILLA   
48         CL       08      39012     009                         LA LLOSA   
49         CL       08      39012     007                   LOS LABRADORES   
50         CL       03   

In [75]:
sdf_cluster2.groupby('PostalCode').count()

StreetType  District  Section  StreetName  Latitude  Longitude  \
PostalCode                                                                   
39001               21        21       21          21        21         21   
39012               66        66       66          66        66         66   

            Cluster Labels  1st Most Common Venue  2nd Most Common Venue  \
PostalCode                                                                 
39001                   21                     21                     21   
39012                   66                     66                     66   

            3rd Most Common Venue  4th Most Common Venue  \
PostalCode                                                 
39001                          21                     21   
39012                          66                     66   

            5th Most Common Venue  6th Most Common Venue  \
PostalCode                                                 
39001                          21                     21   
39012                          66                     66   

            7th Most Common Venue  8th Most Common Venue  \
PostalCode                                                 
39001                          21                     21   
39012                          66                     66   

            9th Most Common Venue  10th Most Common Venue  
PostalCode                                                 
39001                          21                      21  
39012                          66                      66

In [77]:
sdf_cluster2_39012 = sdf_cluster2.drop(sdf_cluster2[ (sdf_cluster2['PostalCode'] != '39012') ].index).reset_index(drop=True)
sdf_cluster2_39012

StreetType District PostalCode Section                       StreetName  \
0          CL       08      39012     012                    INES D. NOVAL   
1          CL       08      39012     024                          SOMONTE   
2          CL       08      39012     009                        CORBANERA   
3          CL       08      39012     024                    MAZO DE ABAJO   
4          CL       08      39012     008                         LA TORRE   
5          CL       08      39012     011                          FUMORIL   
6          AV       08      39012     027             DOCTOR DIEGO MADRAZO   
7          CL       08      39012     009                       SAN MIGUEL   
8          CL       08      39012     011                            CAMUS   
9          CL       08      39012     024                  MANUEL CACICEDO   
10         CL       08      39012     007                          CORCEÑO   
11         CL       08      39012     008                SAN PEDRO DEL MAR   
12         CL       08      39012     024             VICTORIANO FERNANDEZ   
13         CL       08      39012     022                  CONSUELO BERGES   
14         CL       08      39012     008                           BOLADO   
15         CL       08      39012     024                   MAZO DE ARRIBA   
16         CL       08      39012     015                        LA TEJERA   
17         CL       08      39012     008          EDUARDO OBREGON BARREDA   
18         CL       08      39012     016             FRANCISCO DE CACERES   
19         CL       08      39012     011                 HERMANOS TONETTI   
20         CL       08      39012     011                       LA ROCHELA   
21         CL       08      39012     011                       CORCONERAS   
22         CL       08      39012     009                        LA HONDAL   
23         CL       08      39012     012                        LA PEREDA   
24         CL       08      39012     010           PEDRO RODRIGUEZ PARETS   
25         CL       08      39012     007         LAURO FERNANDEZ GONZALEZ   
26         CL       08      39012     015                   LOS PORTUARIOS   
27         CL       08      39012     015                        ALBERICIA   
28         CL       08      39012     007                       EL MIRADOR   
29         CL       08      39012     007       AVIADOR JUAN IGNACIO POMBO   
30         CL       08      39012     027     JOSE MARIA GONZALEZ TREVILLA   
31         CL       08      39012     024                          ROSTRIO   
32         CL       08      39012     011                  RICARDO LORENZO   
33         CL       08      39012     019                        AUTONOMIA   
34         CL       08      39012     009                     LOS BARBAJOS   
35         CL       08      39012     005                  MIES DE MILLAJO   
36         CL       08      39012     012                       BELLAVISTA   
37         CL       08      39012     019                        VALDENOJA   
38         CL       08      39012     007                    LAS PORTILLAS   
39         AV       04      39012     014                        CANTABRIA   
40         CL       08      39012     008  RICARDO FERNANDEZ DE LA REGUERA   
41         CL       08      39012     007                      LA LLANILLA   
42         CL       08      39012     009                         LA LLOSA   
43         CL       08      39012     007                   LOS LABRADORES   
44         CL       08      39012     012                  PEDRO DE ABARCA   
45         CL       08      39012     005                        LA GLORIA   
46         CL       08      39012     027                        EL RECIAL   
47         CL       08      39012     011                         CALVARIO   
48         CL       08      39012     015                        LA PRENSA   
49         CL       08      39012     007              AVIADORES CANTABROS   
50         CL       08   

#### Run k-means to cluster the neighborhood into 5 clusters.

In [78]:
# make a working copy to keep a reference of the original sorted dataframe
streets_venues_sorted5 = streets_venues_sorted.copy()

In [79]:
# set number of clusters
kclusters = 5

sdf_grouped_clustering5 = sdf_grouped.drop('Street', 1)

# run k-means clustering
kmeans5 = KMeans(n_clusters=kclusters, random_state=0).fit(sdf_grouped_clustering5)

# check cluster labels generated for each row in the dataframe
kmeans5.labels_[0:10] 

array([0, 3, 0, 0, 1, 0, 0, 0, 0, 3])

Let's create a new dataframe that includes the cluster as well as the top 10 venues for each street.

In [80]:
streets_venues_sorted5.insert(0, 'Cluster Labels', kmeans5.labels_)

sdf_merged5 = sdf

# merge Santander data in sdf with streets_venues_sorted to add latitude/longitude for each street
sdf_merged5 = sdf_merged5.join(streets_venues_sorted5.set_index('Street'), on='StreetName')

In [81]:
sdf_merged5

StreetType District PostalCode Section                       StreetName  \
0           CL       08      39012     007                   COSTA QUEBRADA   
1           CL       08      39012     012                    INES D. NOVAL   
2           CL       08      39012     007                           CORBAN   
3           CL       07      39012     020                         REPUENTE   
4           CL       07      39012     001                         PRONILLO   
5           CL       08      39012     008                           AVICHE   
6           CL       08      39012     024                          SOMONTE   
7           CL       08      39012     009                        CORBANERA   
8           CL       08      39012     024                    ELENA QUIROGA   
9           CL       08      39012     024                    MAZO DE ABAJO   
10          CL       08      39012     008                         LA TORRE   
11          CL       08      39012     011                          FUMORIL   
12          CL       08      39012     009                         TRISTANA   
13          CL       08      39012     010                           ARRIBA   
14          AV       08      39012     027             DOCTOR DIEGO MADRAZO   
15          CL       01      39001     003                          GUEVARA   
16          CL       08      39012     011                      JESUS OTERO   
17          CL       08      39012     009                       SAN MIGUEL   
18          CL       03      39001     002                          LA LEVA   
19          CL       08      39012     011                            CAMUS   
20          CL       08      39012     024                  MANUEL CACICEDO   
21          CL       08      39012     007                          CORCEÑO   
22          CL       08      39012     008                SAN PEDRO DEL MAR   
23          CL       08      39012     024             VICTORIANO FERNANDEZ   
24          CL       08      39012     024                          EL SOMO   
25          CL       08      39012     022                  CONSUELO BERGES   
26          CL       08      39012     008                           BOLADO   
27          CL       08      39012     024                   MAZO DE ARRIBA   
28          BJ       07      39012     021                         SAN JUAN   
29          AV       07      39012     023                      LOS CASTROS   
30          CL       03      39001     003                   MARIA CRISTINA   
31          CL       08      39012     015                        LA TEJERA   
32          CL       07      39012     021                  JORGE SEPULVEDA   
33          CL       08      39012     008          EDUARDO OBREGON BARREDA   
34          CL       08      39012     016             FRANCISCO DE CACERES   
35          AV       08      39012     024                   VIRGEN DEL MAR   
36          CT       03      39001     002                          ATALAYA   
37          CL       08      39012     011                 HERMANOS TONETTI   
38          GR       07      39012     021    REPUENTE GRUPO FERNANDO ATECA   
39          CL       08      39012     010              MATILDE DE LA TORRE   
40          CL       08      39012     007                       LA CUEVONA   
41          CL       08      39012     011                       LA ROCHELA   
42          CL       08      39012     011                       CORCONERAS   
43          CL       08      39012     007                   SANTA CATALINA   
44          CL       08      39012     009                        LA HONDAL   
45          CL       08      39012     012                        LA PEREDA   
46          CL       07      39012     021               CASTOR AGRA GARCIA   
47          CL       08      39012     010           PEDRO RODRIGUEZ PARETS   
48          CL       08      39012     007         LAURO FERNANDEZ GONZALEZ   
49          CL       08      39012     015            

Finally, let's visualize the resulting clusters

In [82]:
# create map
map_clusters_5 = folium.Map(location=[latitude, longitude], zoom_start=13)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(sdf_merged5['Latitude'], sdf_merged5['Longitude'], sdf_merged5['StreetName'], sdf_merged5['Cluster Labels']):
#   label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    label = folium.Popup(poi + ' Street ')
   
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters_5)
       
map_clusters_5

Cluster with all the streets belonging to postal code 39001 and several from 39012 (in this case,cluster 0)

In [83]:
sdf_cluster5 = sdf_merged5.drop(sdf_merged5[ (sdf_merged5['Cluster Labels'] != 0) ].index).reset_index(drop=True)
sdf_cluster5 

StreetType District PostalCode Section                       StreetName  \
0          CL       08      39012     012                    INES D. NOVAL   
1          CL       08      39012     024                    MAZO DE ABAJO   
2          CL       08      39012     008                         LA TORRE   
3          CL       08      39012     011                          FUMORIL   
4          CL       01      39001     003                          GUEVARA   
5          CL       08      39012     009                       SAN MIGUEL   
6          CL       03      39001     002                          LA LEVA   
7          CL       08      39012     011                            CAMUS   
8          CL       08      39012     007                          CORCEÑO   
9          CL       08      39012     008                           BOLADO   
10         CL       03      39001     003                   MARIA CRISTINA   
11         CL       08      39012     015                        LA TEJERA   
12         CL       07      39012     021                  JORGE SEPULVEDA   
13         CL       08      39012     008          EDUARDO OBREGON BARREDA   
14         CT       03      39001     002                          ATALAYA   
15         CL       08      39012     010              MATILDE DE LA TORRE   
16         CL       08      39012     011                       CORCONERAS   
17         CL       08      39012     009                        LA HONDAL   
18         CL       08      39012     010           PEDRO RODRIGUEZ PARETS   
19         CL       08      39012     015                   LOS PORTUARIOS   
20         CL       08      39012     015                        ALBERICIA   
21         CL       02      39001     021                       JUAN XXIII   
22         CL       08      39012     007                       EL MIRADOR   
23         CL       03      39001     002                    SAN CELEDONIO   
24         CL       08      39012     007       AVIADOR JUAN IGNACIO POMBO   
25         CL       08      39012     024                          ROSTRIO   
26         CL       08      39012     011                  RICARDO LORENZO   
27         CL       08      39012     009                     LOS BARBAJOS   
28         CL       08      39012     005                  MIES DE MILLAJO   
29         CL       08      39012     007                    LAS PORTILLAS   
30         AV       04      39012     014                        CANTABRIA   
31         CL       08      39012     008  RICARDO FERNANDEZ DE LA REGUERA   
32         CL       08      39012     009                         LA LLOSA   
33         CL       08      39012     007                   LOS LABRADORES   
34         CL       03      39001     007                   RIO DE LA PILA   
35         CL       08      39012     012                  PEDRO DE ABARCA   
36         CL       08      39012     005                        LA GLORIA   
37         CL       01      39001     002                         SAN JOSE   
38         CL       03      39001     004                ALSEDO BUSTAMANTE   
39         CL       02      39001     021                     VIA CORNELIA   
40         CL       03      39001     003              AURELIO RUIZ CRESPO   
41         CL       08      39012     015                        LA PRENSA   
42         CL       08      39012     010                            UDIAL   
43         CL       04      39012     014                     ERNEST LLUCH   
44         CL       08      39012     007              AVIADORES CANTABROS   
45         CL       08      39012     010                 MARQUES DE HAZAS   
46         CL       08      39012     027                ARSENIO ODRIOZOLA   
47         CL       07      39012     021         MODESTO MARTINEZ PACHECO   
48         CL       03      39001     002                     VISTA ALEGRE   
49         CL       08      39012     005             LUIS SALGADO LODEIRO   
50         CL       08   

In [84]:
sdf_cluster5.groupby('PostalCode').count()

StreetType  District  Section  StreetName  Latitude  Longitude  \
PostalCode                                                                   
39001               21        21       21          21        21         21   
39012               44        44       44          44        44         44   

            Cluster Labels  1st Most Common Venue  2nd Most Common Venue  \
PostalCode                                                                 
39001                   21                     21                     21   
39012                   44                     44                     44   

            3rd Most Common Venue  4th Most Common Venue  \
PostalCode                                                 
39001                          21                     21   
39012                          44                     44   

            5th Most Common Venue  6th Most Common Venue  \
PostalCode                                                 
39001                          21                     21   
39012                          44                     44   

            7th Most Common Venue  8th Most Common Venue  \
PostalCode                                                 
39001                          21                     21   
39012                          44                     44   

            9th Most Common Venue  10th Most Common Venue  
PostalCode                                                 
39001                          21                      21  
39012                          44                      44

In [87]:
sdf_cluster5_39012 = sdf_cluster5.drop(sdf_cluster5[ (sdf_cluster5['PostalCode'] != '39012') ].index).reset_index(drop=True)
sdf_cluster5_39012

StreetType District PostalCode Section                       StreetName  \
0          CL       08      39012     012                    INES D. NOVAL   
1          CL       08      39012     024                    MAZO DE ABAJO   
2          CL       08      39012     008                         LA TORRE   
3          CL       08      39012     011                          FUMORIL   
4          CL       08      39012     009                       SAN MIGUEL   
5          CL       08      39012     011                            CAMUS   
6          CL       08      39012     007                          CORCEÑO   
7          CL       08      39012     008                           BOLADO   
8          CL       08      39012     015                        LA TEJERA   
9          CL       07      39012     021                  JORGE SEPULVEDA   
10         CL       08      39012     008          EDUARDO OBREGON BARREDA   
11         CL       08      39012     010              MATILDE DE LA TORRE   
12         CL       08      39012     011                       CORCONERAS   
13         CL       08      39012     009                        LA HONDAL   
14         CL       08      39012     010           PEDRO RODRIGUEZ PARETS   
15         CL       08      39012     015                   LOS PORTUARIOS   
16         CL       08      39012     015                        ALBERICIA   
17         CL       08      39012     007                       EL MIRADOR   
18         CL       08      39012     007       AVIADOR JUAN IGNACIO POMBO   
19         CL       08      39012     024                          ROSTRIO   
20         CL       08      39012     011                  RICARDO LORENZO   
21         CL       08      39012     009                     LOS BARBAJOS   
22         CL       08      39012     005                  MIES DE MILLAJO   
23         CL       08      39012     007                    LAS PORTILLAS   
24         AV       04      39012     014                        CANTABRIA   
25         CL       08      39012     008  RICARDO FERNANDEZ DE LA REGUERA   
26         CL       08      39012     009                         LA LLOSA   
27         CL       08      39012     007                   LOS LABRADORES   
28         CL       08      39012     012                  PEDRO DE ABARCA   
29         CL       08      39012     005                        LA GLORIA   
30         CL       08      39012     015                        LA PRENSA   
31         CL       08      39012     010                            UDIAL   
32         CL       04      39012     014                     ERNEST LLUCH   
33         CL       08      39012     007              AVIADORES CANTABROS   
34         CL       08      39012     010                 MARQUES DE HAZAS   
35         CL       08      39012     027                ARSENIO ODRIOZOLA   
36         CL       07      39012     021         MODESTO MARTINEZ PACHECO   
37         CL       08      39012     005             LUIS SALGADO LODEIRO   
38         CL       08      39012     005                 LOS FORAMONTANOS   
39         CL       08      39012     011                            CUETO   
40         CL       08      39012     005          ROY GARCIA DE SANTANDER   
41         CL       08      39012     005                         LAVAPIES   
42         CL       07      39012     021             SOR RAMONA ORMAZABAL   
43         CL       08      39012     010                  CLARA CAMPOAMOR   

     Latitude  Longitude  Cluster Labels     1st Most Common Venue  \
0   43.482780  -3.804766               0               Video Store   
1   43.470427  -3.861043               0                Restaurant   
2   43.475281  -3.815871               0        Italian Restaurant   
3   43.483948  -3.808724               0        Italian Restaurant   
4   43.471029  -3.838252               0      Gym / Fitness Center   
5   43.486326  -3.798123               0                Campground   
6 

#### Run k-means to cluster the neighborhood into 20 clusters.

In [88]:
# make a working copy to keep a reference of the original sorted dataframe
streets_venues_sorted20 = streets_venues_sorted.copy()

In [89]:
# set number of clusters
kclusters = 20

sdf_grouped_clustering20 = sdf_grouped.drop('Street', 1)

# run k-means clustering
kmeans20 = KMeans(n_clusters=kclusters, random_state=0).fit(sdf_grouped_clustering20)

# check cluster labels generated for each row in the dataframe
kmeans20.labels_[0:10] 

array([10,  4,  1,  1, 11,  8,  1,  1,  1,  8])

Let's create a new dataframe that includes the cluster as well as the top 10 venues for each street.

In [90]:
streets_venues_sorted20.insert(0, 'Cluster Labels', kmeans20.labels_)

sdf_merged20 = sdf

# merge Santander data in sdf with streets_venues_sorted to add latitude/longitude for each street
sdf_merged20 = sdf_merged20.join(streets_venues_sorted20.set_index('Street'), on='StreetName')

In [91]:
sdf_merged20

StreetType District PostalCode Section                       StreetName  \
0           CL       08      39012     007                   COSTA QUEBRADA   
1           CL       08      39012     012                    INES D. NOVAL   
2           CL       08      39012     007                           CORBAN   
3           CL       07      39012     020                         REPUENTE   
4           CL       07      39012     001                         PRONILLO   
5           CL       08      39012     008                           AVICHE   
6           CL       08      39012     024                          SOMONTE   
7           CL       08      39012     009                        CORBANERA   
8           CL       08      39012     024                    ELENA QUIROGA   
9           CL       08      39012     024                    MAZO DE ABAJO   
10          CL       08      39012     008                         LA TORRE   
11          CL       08      39012     011                          FUMORIL   
12          CL       08      39012     009                         TRISTANA   
13          CL       08      39012     010                           ARRIBA   
14          AV       08      39012     027             DOCTOR DIEGO MADRAZO   
15          CL       01      39001     003                          GUEVARA   
16          CL       08      39012     011                      JESUS OTERO   
17          CL       08      39012     009                       SAN MIGUEL   
18          CL       03      39001     002                          LA LEVA   
19          CL       08      39012     011                            CAMUS   
20          CL       08      39012     024                  MANUEL CACICEDO   
21          CL       08      39012     007                          CORCEÑO   
22          CL       08      39012     008                SAN PEDRO DEL MAR   
23          CL       08      39012     024             VICTORIANO FERNANDEZ   
24          CL       08      39012     024                          EL SOMO   
25          CL       08      39012     022                  CONSUELO BERGES   
26          CL       08      39012     008                           BOLADO   
27          CL       08      39012     024                   MAZO DE ARRIBA   
28          BJ       07      39012     021                         SAN JUAN   
29          AV       07      39012     023                      LOS CASTROS   
30          CL       03      39001     003                   MARIA CRISTINA   
31          CL       08      39012     015                        LA TEJERA   
32          CL       07      39012     021                  JORGE SEPULVEDA   
33          CL       08      39012     008          EDUARDO OBREGON BARREDA   
34          CL       08      39012     016             FRANCISCO DE CACERES   
35          AV       08      39012     024                   VIRGEN DEL MAR   
36          CT       03      39001     002                          ATALAYA   
37          CL       08      39012     011                 HERMANOS TONETTI   
38          GR       07      39012     021    REPUENTE GRUPO FERNANDO ATECA   
39          CL       08      39012     010              MATILDE DE LA TORRE   
40          CL       08      39012     007                       LA CUEVONA   
41          CL       08      39012     011                       LA ROCHELA   
42          CL       08      39012     011                       CORCONERAS   
43          CL       08      39012     007                   SANTA CATALINA   
44          CL       08      39012     009                        LA HONDAL   
45          CL       08      39012     012                        LA PEREDA   
46          CL       07      39012     021               CASTOR AGRA GARCIA   
47          CL       08      39012     010           PEDRO RODRIGUEZ PARETS   
48          CL       08      39012     007         LAURO FERNANDEZ GONZALEZ   
49          CL       08      39012     015            

Finally, let's visualize the resulting clusters

In [92]:
# create map
map_clusters_20 = folium.Map(location=[latitude, longitude], zoom_start=13)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(sdf_merged20['Latitude'], sdf_merged20['Longitude'], sdf_merged20['StreetName'], sdf_merged20['Cluster Labels']):
#   label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    label = folium.Popup(poi + ' Street ')
   
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters_20)
       
map_clusters_20

Cluster with all the streets belonging to postal code 39001 and several from 39012 (in this case,cluster 1)

In [93]:
sdf_cluster20 = sdf_merged20.drop(sdf_merged20[ (sdf_merged20['Cluster Labels'] != 1) ].index).reset_index(drop=True)
sdf_cluster20 

StreetType District PostalCode Section           StreetName   Latitude  \
0          CL       01      39001     003              GUEVARA  43.465550   
1          CL       03      39001     002              LA LEVA  43.467443   
2          CL       08      39012     011                CAMUS  43.486326   
3          CL       03      39001     003       MARIA CRISTINA  43.468321   
4          CT       03      39001     002              ATALAYA  43.467079   
5          CL       02      39001     021           JUAN XXIII  43.466040   
6          CL       03      39001     002        SAN CELEDONIO  43.466660   
7          CL       08      39012     011      RICARDO LORENZO  43.492528   
8          AV       04      39012     014            CANTABRIA  43.479272   
9          CL       03      39001     007       RIO DE LA PILA  43.468416   
10         CL       08      39012     005            LA GLORIA  43.467476   
11         CL       01      39001     002             SAN JOSE  43.464434   
12         CL       03      39001     004    ALSEDO BUSTAMANTE  43.465899   
13         CL       02      39001     021         VIA CORNELIA  43.467975   
14         CL       03      39001     003  AURELIO RUIZ CRESPO  43.467886   
15         CL       03      39001     002         VISTA ALEGRE  43.467215   
16         CL       08      39012     005     LOS FORAMONTANOS  43.469578   
17         CL       03      39001     002                ASILO  43.466012   
18         CL       01      39001     004             RUALASAL  43.464759   
19         PJ       01      39001     002            ARCILLERO  43.464416   
20         CL       03      39001     005        OBISPO PUCHOL  43.467200   
21         CL       01      39001     006            CERVANTES  43.466087   
22         CL       01      39001     003              SEVILLA  43.465357   
23         CL       02      39001     020            LOS CAÑOS  43.466818   
24         CL       03      39001     008      PRADO SAN ROQUE  43.468491   
25         CL       01      39001     007              FLORIDA  43.464656   

    Longitude  Cluster Labels     1st Most Common Venue 2nd Most Common Venue  \
0   -3.804091               1        Spanish Restaurant                  Café   
1   -3.807361               1                      Café      Tapas Restaurant   
2   -3.798123               1                Campground             BBQ Joint   
3   -3.806775               1                       Bar                  Café   
4   -3.806902               1                      Café      Tapas Restaurant   
5   -3.812874               1                       Bar      Tapas Restaurant   
6   -3.807685               1                      Café                   Bar   
7   -3.796664               1                       Bar            Lighthouse   
8   -3.795595               1                      Park                Bakery   
9   -3.804033               1                       Bar                  Café   
10  -3.841331               1  Bike Rental / Bike Share      Football Stadium   
11  -3.804180               1                      Café      Tapas Restaurant   
12  -3.805460               1        Spanish Restaurant                   Bar   
13  -3.810516               1                      Café          Concert Hall   
14  -3.804864               1                       Bar                  Café   
15  -3.808073               1                      Café                   Bar   
16  -3.841350               1  Bike Rental / Bike Share      Football Stadium   
17  -3.808504               1                      Café      Tapas Restaurant   
18  -3.805086               1                       Bar                  Café   
19  -3.805333               1                      Café                   Bar   
20  -3.804880               1                       Bar                  Café   
21  -3.809841               1                      Café      Tapas Restaurant   
22  -3.805010               1                      Café     

In [94]:
sdf_cluster20.groupby('PostalCode').count()

StreetType  District  Section  StreetName  Latitude  Longitude  \
PostalCode                                                                   
39001               21        21       21          21        21         21   
39012                5         5        5           5         5          5   

            Cluster Labels  1st Most Common Venue  2nd Most Common Venue  \
PostalCode                                                                 
39001                   21                     21                     21   
39012                    5                      5                      5   

            3rd Most Common Venue  4th Most Common Venue  \
PostalCode                                                 
39001                          21                     21   
39012                           5                      5   

            5th Most Common Venue  6th Most Common Venue  \
PostalCode                                                 
39001                          21                     21   
39012                           5                      5   

            7th Most Common Venue  8th Most Common Venue  \
PostalCode                                                 
39001                          21                     21   
39012                           5                      5   

            9th Most Common Venue  10th Most Common Venue  
PostalCode                                                 
39001                          21                      21  
39012                           5                       5

In [95]:
sdf_cluster20_39012 = sdf_cluster20.drop(sdf_cluster20[ (sdf_cluster20['PostalCode'] != '39012') ].index).reset_index(drop=True)
sdf_cluster20_39012

StreetType District PostalCode Section        StreetName   Latitude  \
0         CL       08      39012     011             CAMUS  43.486326   
1         CL       08      39012     011   RICARDO LORENZO  43.492528   
2         AV       04      39012     014         CANTABRIA  43.479272   
3         CL       08      39012     005         LA GLORIA  43.467476   
4         CL       08      39012     005  LOS FORAMONTANOS  43.469578   

   Longitude  Cluster Labels     1st Most Common Venue 2nd Most Common Venue  \
0  -3.798123               1                Campground             BBQ Joint   
1  -3.796664               1                       Bar            Lighthouse   
2  -3.795595               1                      Park                Bakery   
3  -3.841331               1  Bike Rental / Bike Share      Football Stadium   
4  -3.841350               1  Bike Rental / Bike Share      Football Stadium   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
0                   Bar            Lighthouse           Snack Place   
1              Wine Bar      Department Store        Clothing Store   
2    Mexican Restaurant                 Hotel  Gym / Fitness Center   
3           Coffee Shop              Boutique              Wine Bar   
4           Coffee Shop              Wine Bar        Clothing Store   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
0      Department Store          Cocktail Bar           Coffee Shop   
1          Cocktail Bar           Coffee Shop          Concert Hall   
2         Grocery Store                  Café           Snack Place   
3          Cocktail Bar          Concert Hall     Convenience Store   
4          Cocktail Bar          Concert Hall     Convenience Store   

  9th Most Common Venue 10th Most Common Venue  
0          Concert Hall      Convenience Store  
1     Convenience Store      Convention Center  
2    Seafood Restaurant             Theme Park  
3     Convention Center       Department Store  
4     Convention Center       Department Store

## Results and Discussion <a name="results"></a>

At this point, we have made a triple analysis: from minimum possible number of clusters to a potential maximum.
And our results have been the following in each case:
   - 2 clusters: Cluster 1 has the 21 streets situated in the downtonw and 66 streets belonging to the suburbs.
   - 5 clusters: Cluster 0 has the 21 streets situated in the downtown and 44 streets belonging to the suburbs.
   - 20 clusters: Cluster 1 has the 21 streets situated in the downtown and 5 streets belonging to the suburbs.

So, as we increase the number of clusters, we see how the number of similar streets between both areas decreases, 
reaching a miminum of 5 streets in the suburbs clustered in the same label that all of the center ones.
So we can say that streets in postal code 39012 most alike to those in 39001 are:
    

In [96]:
sdf_cluster20_39012

StreetType District PostalCode Section        StreetName   Latitude  \
0         CL       08      39012     011             CAMUS  43.486326   
1         CL       08      39012     011   RICARDO LORENZO  43.492528   
2         AV       04      39012     014         CANTABRIA  43.479272   
3         CL       08      39012     005         LA GLORIA  43.467476   
4         CL       08      39012     005  LOS FORAMONTANOS  43.469578   

   Longitude  Cluster Labels     1st Most Common Venue 2nd Most Common Venue  \
0  -3.798123               1                Campground             BBQ Joint   
1  -3.796664               1                       Bar            Lighthouse   
2  -3.795595               1                      Park                Bakery   
3  -3.841331               1  Bike Rental / Bike Share      Football Stadium   
4  -3.841350               1  Bike Rental / Bike Share      Football Stadium   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
0                   Bar            Lighthouse           Snack Place   
1              Wine Bar      Department Store        Clothing Store   
2    Mexican Restaurant                 Hotel  Gym / Fitness Center   
3           Coffee Shop              Boutique              Wine Bar   
4           Coffee Shop              Wine Bar        Clothing Store   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
0      Department Store          Cocktail Bar           Coffee Shop   
1          Cocktail Bar           Coffee Shop          Concert Hall   
2         Grocery Store                  Café           Snack Place   
3          Cocktail Bar          Concert Hall     Convenience Store   
4          Cocktail Bar          Concert Hall     Convenience Store   

  9th Most Common Venue 10th Most Common Venue  
0          Concert Hall      Convenience Store  
1     Convenience Store      Convention Center  
2    Seafood Restaurant             Theme Park  
3     Convention Center       Department Store  
4     Convention Center       Department Store

## Conclusion <a name="conclusion"></a>

Our goal when starting this project was, by means of joining data from two main sources, the city of Santander's open repository
and Foursquare, make a comparison between two areas of the city, the very center and the outer most suburb, in order to 
find out which places in the latter would be similar to the ones in the former in terms of venues and places to go.
And, as we have already seen, our analysis have showed that there are 5 possible candidates to be considered. In other words,
5 streets in the suburbs similar to the downtown.